Repository milzipmoza-developers/tecobrary-server-api-v2, pull requests merged in 2019-12, with the labels that each got.

#33 [#10, #11] 유저를 조회한다.
  src/main/java/com/woowacourse/tecobrary/user/command/application/NotFoundUserException.java
  src/main/java/com/woowacourse/tecobrary/user/command/application/UserService.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/User.java
  src/main/java/com/woowacourse/tecobrary/user/command/util/UserInfoDtoMapper.java
  src/main/java/com/woowacourse/tecobrary/user/ui/UserController.java
  src/main/java/com/woowacourse/tecobrary/user/ui/dto/UserInfoDto.java
  src/test/java/com/woowacourse/tecobrary/user/command/application/UserServiceTest.java
  src/test/java/com/woowacourse/tecobrary/user/common/GithubApiStatic.java
  src/test/java/com/woowacourse/tecobrary/user/common/UserStatic.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
Labels: enhancement

#36 [#34] 도서를 조회하는 기능을 구현한다.
  src/main/java/com/woowacourse/tecobrary/librarybook/application/LibraryBookService.java
  src/main/java/com/woowacourse/tecobrary/librarybook/domain/LibraryBook.java
  src/main/java/com/woowacourse/tecobrary/librarybook/domain/LibraryBookRepository.java
  src/main/java/com/woowacourse/tecobrary/librarybook/exception/NotFoundLibraryBookException.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookController.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerAdvice.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/dto/LibraryBookCreateResponseDto.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/dto/LibraryBookRequestDto.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/dto/LibraryBookResponseDto.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/dto/LibraryBookTotalCountResponseDto.java
  src/main/java/com/woowacourse/tecobrary/librarybook/util/LibraryBookMapper.java
  src/test/java/com/woowacourse/tecobrary/librarybook/application/LibraryBookServiceTest.java
  src/test/java/com/woowacourse/tecobrary/librarybook/common/LibraryBookStatic.java
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/resources/data.sql
Labels: enhancement

#51 [#15] 회원의 닉네임을 업데이트한다.
  src/main/java/com/woowacourse/tecobrary/user/command/application/UserService.java
  src/main/java/com/woowacourse/tecobrary/user/ui/UserController.java
  src/main/java/com/woowacourse/tecobrary/user/ui/dto/UserNameDto.java
  src/test/java/com/woowacourse/tecobrary/user/command/application/UserServiceTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
Labels: enhancement

#53 [#48] 특정 도서에 serial을 추가한다.
  src/main/java/com/woowacourse/tecobrary/librarybook/application/LibraryBookService.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialCreateService.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialService.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/Serial.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialInfo.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialRepository.java
  src/main/java/com/woowacourse/tecobrary/serial/exception/NotFoundSerialTargetException.java
  src/main/java/com/woowacourse/tecobrary/serial/exception/UniqueConstraintException.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/SerialControllerAdvice.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/SerialCreateController.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/dto/SerialCreateRequestDto.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/dto/SerialCreateResponseDto.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/dto/SerialResponseDto.java
  src/main/java/com/woowacourse/tecobrary/serial/util/SerialMapper.java
  src/test/java/com/woowacourse/tecobrary/serial/application/SerialCreateServiceTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateControllerTest.java
  src/test/resources/data.sql
Labels: enhancement

#66 [#57] 회원의 도서 대여목록을 반환한다.
  src/main/java/com/woowacourse/tecobrary/librarybook/application/LibraryBookService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistory.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryRepository.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryController.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentHistoryDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/util/RentHistoryMapper.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialService.java
  src/test/java/com/woowacourse/tecobrary/librarybook/common/LibraryBookStatic.java
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/common/RentHistoryStatic.java
  src/test/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryRepositoryTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/common/SerialStatic.java
Labels: enhancement

#73 [#70] Advice를 추가하고, 조회할 때 등록되지 않은 도서만 조회한다.
  src/main/java/com/woowacourse/tecobrary/wishbook/command/application/WishBookService.java
  src/main/java/com/woowacourse/tecobrary/wishbook/command/domain/WishBookRepository.java
  src/main/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerAdvice.java
  src/test/java/com/woowacourse/tecobrary/wishbook/command/application/WishBookServiceTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/command/domain/WishBookRepositoryTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerTest.java
Labels: enhancement

#91 [#89] docker 실행 후 DB 초기화 시 한글이 깨져서 초기화 되는 것을 해결한다.
  docker/cnf/my.cnf
  docker/docker-compose.yml
Labels: bug

#92 [#59] serial과 userId 를 받아 도서 대여를 처리한다.
  src/main/java/com/woowacourse/tecobrary/librarybook/application/LibraryBookService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/AlreadyRentBookException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentReturnService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryControllerAdvice.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadController.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnController.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentInfoDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentRequestDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentResponseDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/util/RentHistoryMapper.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialService.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/Serial.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialRentStatus.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialRepository.java
  src/main/java/com/woowacourse/tecobrary/serial/exception/AlreadyRentStatusException.java
  src/main/java/com/woowacourse/tecobrary/serial/exception/NotFoundSerialNumberException.java
  src/main/java/com/woowacourse/tecobrary/user/command/application/UserService.java
  src/main/java/com/woowacourse/tecobrary/user/ui/UserControllerAdvice.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentReturnServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/common/RentHistoryStatic.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/common/SerialStatic.java
  src/test/java/com/woowacourse/tecobrary/serial/domain/SerialTest.java
Labels: enhancement

#94 [#60] serial 과 userId 를 받아 도서 반납을 처리한다.
  src/main/java/com/woowacourse/tecobrary/renthistory/application/AlreadyRentBookException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/AlreadyReturnBookException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/NotFoundRentHistoryException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentReturnService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/NotPermittedUserException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistory.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryRepository.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentUser.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryControllerAdvice.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnController.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentHistoryRequest.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentHistoryRequestDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentHistoryResponseDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentRequestDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/RentResponseDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/ReturnInfoDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/ReturnRequestDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/ReturnResponseDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/util/RentHistoryMapper.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/Serial.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialRentStatus.java
  src/main/java/com/woowacourse/tecobrary/serial/exception/AlreadyReturnStatusException.java
  src/main/java/com/woowacourse/tecobrary/serial/util/SerialMapper.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentReturnServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryRepositoryTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/application/SerialServiceTest.java
  src/test/java/com/woowacourse/tecobrary/serial/common/SerialStatic.java
  src/test/java/com/woowacourse/tecobrary/serial/domain/SerialTest.java
  src/test/resources/data.sql
Labels: enhancement

#98 [#85] Spring REST Docs를 적용한다.
  build.gradle
  src/docs/asciidoc/librarybook/librarybook.adoc
  src/docs/asciidoc/librarybook/successfully-create-library-book.adoc
  src/docs/asciidoc/librarybook/successfully-read-library-book-total-count.adoc
  src/docs/asciidoc/librarybook/successfully-read-library-book.adoc
  src/docs/asciidoc/librarybook/successfully-read-library-books-by-title.adoc
  src/docs/asciidoc/librarybook/successfully-read-library-books.adoc
  src/docs/asciidoc/main.adoc
  src/docs/asciidoc/renthistory/renthistory.adoc
  src/docs/asciidoc/renthistory/successfully-find-all-rent-history-by-user.adoc
  src/docs/asciidoc/renthistory/successfully-rent-a-book.adoc
  src/docs/asciidoc/renthistory/successfully-return-a-book.adoc
  src/docs/asciidoc/serial/serial.adoc
  src/docs/asciidoc/serial/successfully-create-serial.adoc
  src/docs/asciidoc/serial/successfully-get-book-Id-serials.adoc
  src/docs/asciidoc/serial/successfully-remove-serial.adoc
  src/docs/asciidoc/user/successfully-count-of-user.adoc
  src/docs/asciidoc/user/successfully-find-user-by-id.adoc
  src/docs/asciidoc/user/successfully-find-users.adoc
  src/docs/asciidoc/user/successfully-update-user-auth.adoc
  src/docs/asciidoc/user/successfully-update-user-nick-name.adoc
  src/docs/asciidoc/user/user.adoc
  src/docs/asciidoc/wishbook/successfully-create-wish-book.adoc
  src/docs/asciidoc/wishbook/successfully-delete-wish-book.adoc
  src/docs/asciidoc/wishbook/successfully-enroll.adoc
  src/docs/asciidoc/wishbook/successfully-find-wish-books.adoc
  src/docs/asciidoc/wishbook/wishbook.adoc
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookEnrollControllerTest.java
Labels: enhancement, study

#101 [#100] 테스트 코드의 중복을 제거한다.
  src/test/java/com/woowacourse/tecobrary/common/ui/ApiIndexControllerTest.java
  src/test/java/com/woowacourse/tecobrary/common/util/AcceptanceTestUtils.java
  src/test/java/com/woowacourse/tecobrary/common/util/RestAssuredTestUtils.java
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/GithubUserApiControllerTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookEnrollControllerTest.java
Labels: duplicate

#106 [#102] 문서화하지 않은 인수테스트를 문서화한다.
  src/docs/asciidoc/librarybook/failed-create-library-books.adoc
  src/docs/asciidoc/librarybook/failed-read-library-book.adoc
  src/docs/asciidoc/librarybook/failed-read-library-books.adoc
  src/docs/asciidoc/librarybook/librarybook.adoc
  src/docs/asciidoc/renthistory/failed-rent-with-already-rent-serial.adoc
  src/docs/asciidoc/renthistory/failed-rent-with-not-exist-serial.adoc
  src/docs/asciidoc/renthistory/failed-rent-with-not-exist-user.adoc
  src/docs/asciidoc/renthistory/failed-return-with-already-rent-serial.adoc
  src/docs/asciidoc/renthistory/failed-return-with-not-exist-serial.adoc
  src/docs/asciidoc/renthistory/failed-return-with-not-exist-user.adoc
  src/docs/asciidoc/renthistory/failed-return-with-not-rent-user.adoc
  src/docs/asciidoc/renthistory/renthistory.adoc
  src/docs/asciidoc/serial/failed-create-serial-not-found-serial-target.adoc
  src/docs/asciidoc/serial/failed-create-serial-unique-constraint.adoc
  src/docs/asciidoc/serial/failed-get-book-id-serials-bad-request.adoc
  src/docs/asciidoc/serial/failed-remove-serial-not-exist-id.adoc
  src/docs/asciidoc/serial/serial.adoc
  src/docs/asciidoc/user/fail-find-users-invalid-params.adoc
  src/docs/asciidoc/user/fail-find-users.adoc
  src/docs/asciidoc/user/user.adoc
  src/docs/asciidoc/wishbook/failed-created-wish-book.adoc
  src/docs/asciidoc/wishbook/failed-enroll-already-soft-deleted.adoc
  src/docs/asciidoc/wishbook/failed-enroll-not-found-wish-book-id.adoc
  src/docs/asciidoc/wishbook/wishbook.adoc
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookEnrollControllerTest.java
Labels: documentation

#109 [#107] 인수테스트의 DisplayName이 테스트를 잘 설명하도록 수정한다.
  src/docs/asciidoc/librarybook/librarybook.adoc
  src/docs/asciidoc/renthistory/renthistory.adoc
  src/docs/asciidoc/serial/serial.adoc
  src/docs/asciidoc/user/user.adoc
  src/docs/asciidoc/wishbook/wishbook.adoc
  src/test/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentReturnControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/user/ui/UserControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookControllerTest.java
  src/test/java/com/woowacourse/tecobrary/wishbook/ui/WishBookEnrollControllerTest.java
Labels: refactor

#119 [#108] serialNumber 로 책 정보를 조회하는 기능을 추가한다.
  build.gradle
  src/docs/asciidoc/serial/failed-get-book-by-serial-number-not-exist.adoc
  src/docs/asciidoc/serial/serial.adoc
  src/docs/asciidoc/serial/successfully-get-book-by-serial-number.adoc
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialCreateReadService.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadController.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialCreateReadControllerTest.java
Labels: enhancement

#122 [#54] 컨벤션에 맞춰서 final을 추가한다.
  src/main/java/com/woowacourse/tecobrary/common/infra/filter/CorsFilter.java
  src/main/java/com/woowacourse/tecobrary/common/infra/filter/JwtFilter.java
  src/main/java/com/woowacourse/tecobrary/common/model/BookCoverUrl.java
  src/main/java/com/woowacourse/tecobrary/common/model/BookInfo.java
  src/main/java/com/woowacourse/tecobrary/common/model/Email.java
  src/main/java/com/woowacourse/tecobrary/common/model/HttpsUrl.java
  src/main/java/com/woowacourse/tecobrary/common/util/BodyParser.java
  src/main/java/com/woowacourse/tecobrary/librarybook/domain/LibraryBook.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookController.java
  src/main/java/com/woowacourse/tecobrary/librarybook/ui/dto/LibraryBookRequestDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/NotFoundRentHistoryException.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistory.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentSerial.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentUser.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadController.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialCreateReadService.java
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialService.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/Serial.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialLibraryBook.java
  src/main/java/com/woowacourse/tecobrary/serial/domain/SerialRentStatus.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/SerialController.java
  src/main/java/com/woowacourse/tecobrary/serial/util/SerialMapper.java
  src/main/java/com/woowacourse/tecobrary/user/command/application/UserGithubService.java
  src/main/java/com/woowacourse/tecobrary/user/command/application/UserService.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/Authorization.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/User.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/UserAuthorization.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/UserGithubInfo.java
  src/main/java/com/woowacourse/tecobrary/user/command/domain/UserName.java
  src/main/java/com/woowacourse/tecobrary/user/command/util/UserGithubInfoMapper.java
  src/main/java/com/woowacourse/tecobrary/user/command/util/UserJwtVoMapper.java
  src/main/java/com/woowacourse/tecobrary/user/infra/dto/UserGithubInfoDto.java
  src/main/java/com/woowacourse/tecobrary/user/infra/util/GithubUserApiUrlBuilder.java
  src/main/java/com/woowacourse/tecobrary/user/infra/util/GsonUtils.java
  src/main/java/com/woowacourse/tecobrary/user/infra/util/JwtUtils.java
  src/main/java/com/woowacourse/tecobrary/user/ui/GithubOAuthController.java
  src/main/java/com/woowacourse/tecobrary/user/ui/GithubUserApiController.java
  src/main/java/com/woowacourse/tecobrary/user/ui/JwtAuthenticationController.java
  src/main/java/com/woowacourse/tecobrary/user/ui/UserController.java
  src/main/java/com/woowacourse/tecobrary/utility/YamlPropertiesProcessor.java
  src/main/java/com/woowacourse/tecobrary/utility/YamlPropertySourceFactory.java
  src/main/java/com/woowacourse/tecobrary/utility/YamlResourcePropertySource.java
  src/main/java/com/woowacourse/tecobrary/wishbook/command/application/WishBookEnrollService.java
  src/main/java/com/woowacourse/tecobrary/wishbook/command/domain/WishBook.java
  src/main/java/com/woowacourse/tecobrary/wishbook/command/domain/WishBookRequestUser.java
  src/main/java/com/woowacourse/tecobrary/wishbook/ui/WishBookController.java
  src/main/java/com/woowacourse/tecobrary/wishbook/ui/WishBookEnrollController.java
Labels: refactor

#135 [#133] 반납이 완료된 RentHistory 를 구하는 기능을 구현한다.
  src/docs/asciidoc/renthistory/renthistory.adoc
  src/docs/asciidoc/renthistory/successfully-find-all-return-history-by-user.adoc
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryService.java
  src/main/java/com/woowacourse/tecobrary/renthistory/domain/RentHistoryRepository.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadController.java
  src/main/java/com/woowacourse/tecobrary/renthistory/ui/dto/ReturnHistoryDto.java
  src/main/java/com/woowacourse/tecobrary/renthistory/util/RentHistoryMapper.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentHistoryReadServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/application/RentReturnServiceTest.java
  src/test/java/com/woowacourse/tecobrary/renthistory/common/RentHistoryStatic.java
  src/test/java/com/woowacourse/tecobrary/renthistory/ui/RentHistoryReadControllerTest.java
  src/test/java/com/woowacourse/tecobrary/serial/common/SerialStatic.java
Labels: enhancement

#137 [#136] UserJwtVoMapper toVo 에 누락된 필드를 추가한다.
  src/main/java/com/woowacourse/tecobrary/user/command/util/UserJwtVoMapper.java
  src/main/java/com/woowacourse/tecobrary/user/infra/util/JwtUtils.java
  src/main/java/com/woowacourse/tecobrary/user/ui/vo/UserJwtInfoVo.java
  src/test/java/com/woowacourse/tecobrary/user/common/UserStatic.java
  src/test/java/com/woowacourse/tecobrary/user/infra/util/JwtUtilsTest.java
Labels: bug

#138 [#120] Serial을 삭제할 때 대여중인지 확인하는 로직을 추가한다.
  src/main/java/com/woowacourse/tecobrary/serial/application/SerialService.java
  src/main/java/com/woowacourse/tecobrary/serial/ui/SerialControllerAdvice.java
  src/test/java/com/woowacourse/tecobrary/serial/ui/SerialControllerTest.java
Labels: enhancement
